### ISSUE TITLE
Issue tracking the implemented ein-strings

### ISSUE THREAD

**Issue by scarlehoff** [Amps-GPU/BG-Trees#2]
The issue keeps tracks of the einsum strings that can be fully ran in GPU without integer overflows.
Some of them need to be implemented as custom cuda kernels, others might be runnable with some transposition of axes (for instance the first few one are just an axis permutation).

For now this is the list of strings that appear in [this notebook](https://github.com/Amps-GPU/notebooks/blob/main/PyadicFiniteField_comparison_TF.ipynb) so it is not necessarily complete.

- [x] lnmo->lmno
- [x] mnl->lmn

The ones below are assumed to be batched in every tensor but it is omitted so it looks like in the notebook (so `ij, jk -> ik` would be a batch of 2d arrays x and and another batch of 2d arrays y)

2x3
- [x] xa,mab->mb (the op missing is `xa , mab -> xmb`)

Special cases of 2x2
- [x] mb,bx->m (this corresponds to `mb, bx-> mx` then `reduce_sum(tensor, axis=-1)`)
- [x] xa,ay-> (this corresponds to `xa, ay-> xy` then `reduce_sum(tensor, axis=(-2,-1)`)
- [x] i,ij,j-> (this corresponds to `i, ij->j` then `j, j->`, already implemented by adding 1-d dimension as extra)

Missing:

- [x] Same as above but when only one of the arrays is batched. Probably a few things can be optimized out and makes sense to compile two kernels.

Of course, all 2x2 cases are a special case of 2x3 so will probably implement that first then specialize down.

Note: ideally we will do it automagically but it might not always be possible.
